name: Linter
on: [push]
jobs:
  ktlint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      #Linter
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
  test:
    #Setup
    - uses: actions/checkout@v1
    #Unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless