name: Code Analyze

on:
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle
      - name: Run Gradle tasks
        run: ./gradlew detekt
        continue-on-error: true
      - name: Stop Gradle
        run: ./gradlew --stop
      - name: Run reviewdog