name: Code Analyze

on:
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Build
        run: ~/.gradlew build
      - name: Run reviewdog
        run: ~/.gradlew lint